import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
const axios = require("axios").default;

const Home = ({ parties }) => {
  return (
    <div className='container mt-3'>
      <Head>
        <title>Political Parties in India</title>
        <meta name="description" content="Generated by create next app - vipin singh" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h3>Political Parties in India</h3>
        <div className='row mt-3'>
          {parties.map((party) => {
            return (
              <div className='col-md-4'>
                <div className="card">
                  <div className="card-body">
                    <h5 className="card-title">{party.name}</h5>
                    <h6 className="card-subtitle mb-2 text-muted">{party.short_name}</h6>
                    <p className="card-text">Election Symbol : {party.election_symbol}</p>
                    <Link href={`/${party._id}`}>
                      <button className="btn btn-primary me-2">View Details</button>
                    </Link>
                    <Link href={`/${party._id}/update`}>
                      <button className="btn btn-secondary ml-2">Edit Details</button>
                    </Link>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
    </div>
  )
}

// fetch data from api using server side rendering method
export async function getServerSideProps(context){
  const res = await axios("http://localhost:3000/api/party/")
  const { party } = res.data
  return {
    props : {parties : party}
  }
}

export default Home